# Generated by Django 6.0rc1 on 2026-01-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("votes", "0006_election_required_webgroups_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="election",
            name="required_webgroups",
            field=models.JSONField(
                default=list, help_text="Required webgroups to be eligible to vote"
            ),
        ),
        migrations.AlterField(
            model_name="election",
            name="self_id_eligibility_confirmation",
            field=models.TextField(
                blank=True,
                help_text="Confirmation text when the vote is restricted, but permits self-ID",
            ),
        ),
    ]
