# Generated by Django 6.0rc1 on 2026-01-17 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uwcs_auth', '0003_sumember_alter_warwickvoteuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sumember',
            name='webgroups',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
