# Generated by Django 6.0rc1 on 2026-02-20 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("uwcs_auth", "0004_sumember_webgroups"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SUMember",
        ),
    ]
